package shell

import (
	"fmt"
	"strings"
)

// ShellDialect encapsulates syntax differences between shell languages.
// Implementing this interface is all that's needed to add support for a
// new shell (e.g. fish, powershell) to PI's shortcut generation.
type ShellDialect interface {
	// EvalWrapperFunc generates a complete shell function that:
	//   1. Creates a temp file for parent-shell eval
	//   2. Runs innerCmd with PI_PARENT_EVAL_FILE pointing to the temp file
	//   3. Captures the exit code
	//   4. Sources the eval file if non-empty
	//   5. Cleans up the temp file
	//   6. Returns the captured exit code
	EvalWrapperFunc(funcName, innerCmd string) string

	// InRepoCmd wraps a pi command so it runs from repoRoot (cd + subshell).
	InRepoCmd(repoRoot, piCmd string) string

	// AnywhereCmd wraps a pi command so it runs from anywhere (--repo flag).
	AnywhereCmd(repoRoot, piBinary, piArgs string) string

	// AllArgs returns the syntax for forwarding all arguments (e.g. "$@").
	AllArgs() string

	// FileHeader returns a comment block for the top of generated files.
	FileHeader(project, repoRoot string) string
}

// BashDialect generates shell functions in bash/zsh syntax.
type BashDialect struct{}

func (d BashDialect) EvalWrapperFunc(funcName, innerCmd string) string {
	return fmt.Sprintf(`function %s() {
  local _pi_eval_file
  _pi_eval_file="$(mktemp)"
  %s
  local _pi_exit=$?
  if [ -s "$_pi_eval_file" ]; then
    source "$_pi_eval_file"
  fi
  rm -f "$_pi_eval_file"
  return $_pi_exit
}
`, funcName, innerCmd)
}

func (d BashDialect) InRepoCmd(repoRoot, piCmd string) string {
	return fmt.Sprintf(`(cd %q && %s)`, repoRoot, piCmd)
}

func (d BashDialect) AnywhereCmd(repoRoot, piBinary, piArgs string) string {
	return fmt.Sprintf(`%s --repo %q %s`, piBinary, repoRoot, piArgs)
}

func (d BashDialect) AllArgs() string {
	return `"$@"`
}

func (d BashDialect) FileHeader(project, repoRoot string) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("# PI shortcuts for %s\n", project))
	b.WriteString(fmt.Sprintf("# Repo: %s\n", repoRoot))
	b.WriteString("# Auto-generated by: pi shell — do not edit manually\n\n")
	return b.String()
}

// DefaultDialect returns the standard bash/zsh dialect.
func DefaultDialect() ShellDialect {
	return BashDialect{}
}
