package shell

import (
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/vyper-tooling/pi/internal/config"
)

const (
	piShellDir       = ".pi/shell"
	piWrapperFile    = "_pi-wrapper.sh"
	piCompletionFile = "_pi-completion.sh"
	sourceBlock      = "\n# Added by PI — do not edit\nfor f in \"$HOME/.pi/shell/\"*.sh; do [ -f \"$f\" ] && source \"$f\"; done\n"

	piFishWrapperFile    = "_pi-wrapper.fish"
	piFishCompletionFile = "_pi-completion.fish"
	fishSourceBlock      = "\n# Added by PI — do not edit\nfor f in ~/.pi/shell/*.fish\n  test -f $f; and source $f\nend\n"
)

// ShellFileDir returns ~/.pi/shell/.
func ShellFileDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("getting home directory: %w", err)
	}
	return filepath.Join(home, piShellDir), nil
}

// ShellFilePath returns ~/.pi/shell/<project>.sh.
func ShellFilePath(project string) (string, error) {
	dir, err := ShellFileDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, project+".sh"), nil
}

// FishFilePath returns ~/.pi/shell/<project>.fish.
func FishFilePath(project string) (string, error) {
	dir, err := ShellFileDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, project+".fish"), nil
}

// GenerateShellFile builds the content of the shortcuts shell file for a project.
// piBinary is the path to the pi binary (resolved by the caller).
// repoRoot is the absolute path to the project root.
func GenerateShellFile(cfg *config.ProjectConfig, piBinary, repoRoot string) string {
	return GenerateShellFileWithDialect(cfg, piBinary, repoRoot, DefaultDialect())
}

// GenerateShellFileWithDialect builds the content using the given shell dialect.
func GenerateShellFileWithDialect(cfg *config.ProjectConfig, piBinary, repoRoot string, d ShellDialect) string {
	if len(cfg.Shortcuts) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString(d.FileHeader(cfg.Project, repoRoot))

	b.WriteString(generateSetupHelper(piBinary, repoRoot, d))
	b.WriteString("\n")

	names := sortedShortcutNames(cfg.Shortcuts)

	for _, name := range names {
		sc := cfg.Shortcuts[name]
		b.WriteString(generateFunction(name, sc, piBinary, repoRoot, d))
		b.WriteString("\n")
	}

	return b.String()
}

// generateSetupHelper emits a pi-setup-<project> function that wraps `pi setup`
// with the eval pattern so that post-setup shell sourcing works automatically.
func generateSetupHelper(piBinary, repoRoot string, d ShellDialect) string {
	safeProject := strings.ReplaceAll(filepath.Base(repoRoot), " ", "-")
	funcName := "pi-setup-" + safeProject
	piCmd := fmt.Sprintf(`PI_PARENT_EVAL_FILE="$_pi_eval_file" %s setup %s`, piBinary, d.AllArgs())
	innerCmd := d.InRepoCmd(repoRoot, piCmd)
	return d.EvalWrapperFunc(funcName, innerCmd)
}

func generateFunction(name string, sc config.Shortcut, piBinary, repoRoot string, d ShellDialect) string {
	suffix := d.AllArgs()
	if len(sc.With) > 0 {
		suffix = buildWithArgs(sc.With, d)
	}

	piRunArgs := fmt.Sprintf("run %s %s", sc.Run, suffix)
	piCmd := fmt.Sprintf(`PI_PARENT_EVAL_FILE="$_pi_eval_file" %s %s`, piBinary, piRunArgs)

	var innerCmd string
	if sc.Anywhere {
		innerCmd = d.AnywhereCmd(repoRoot, fmt.Sprintf(`PI_PARENT_EVAL_FILE="$_pi_eval_file" %s`, piBinary), piRunArgs)
	} else {
		innerCmd = d.InRepoCmd(repoRoot, piCmd)
	}
	return d.EvalWrapperFunc(name, innerCmd)
}

func buildWithArgs(with map[string]string, d ShellDialect) string {
	withNames := slices.Sorted(maps.Keys(with))

	var withParts []string
	for _, k := range withNames {
		v := with[k]
		if isPositionalRef(v) {
			argNum := v[1:]
			withParts = append(withParts, fmt.Sprintf("--with %s=%s", k, d.PositionalArg(argNum)))
		} else {
			withParts = append(withParts, fmt.Sprintf("--with %s=%q", k, v))
		}
	}
	return strings.Join(withParts, " ")
}

func isPositionalRef(v string) bool {
	if len(v) < 2 || v[0] != '$' {
		return false
	}
	for _, c := range v[1:] {
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}

// GenerateGlobalWrapper builds the content of the global pi() shell function.
// This wraps every `pi` invocation with the eval pattern so parent_shell steps
// work for all `pi run` calls, not just shortcuts.
func GenerateGlobalWrapper(piBinary string) string {
	return GenerateGlobalWrapperWithDialect(piBinary, DefaultDialect())
}

// GenerateGlobalWrapperWithDialect generates the wrapper using the given dialect.
func GenerateGlobalWrapperWithDialect(piBinary string, d ShellDialect) string {
	innerCmd := fmt.Sprintf(`PI_PARENT_EVAL_FILE="$_pi_eval_file" command %s %s`, piBinary, d.AllArgs())
	header := "# PI global wrapper — enables parent_shell steps for all pi invocations\n# Auto-generated by: pi shell — do not edit manually\n"
	return header + d.EvalWrapperFunc("pi", innerCmd)
}

// Install writes the shortcuts file, the global pi() wrapper,
// and ensures the source line is in shell configs.
// When fish shell is detected, fish-syntax files are also generated.
func Install(cfg *config.ProjectConfig, piBinary, repoRoot string) (string, error) {
	content := GenerateShellFile(cfg, piBinary, repoRoot)
	if content == "" {
		return "", fmt.Errorf("no shortcuts defined in pi.yaml")
	}

	shellPath, err := ShellFilePath(cfg.Project)
	if err != nil {
		return "", err
	}

	if err := os.MkdirAll(filepath.Dir(shellPath), 0o755); err != nil {
		return "", fmt.Errorf("creating shell directory: %w", err)
	}

	if err := os.WriteFile(shellPath, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("writing shell file: %w", err)
	}

	shellDir := filepath.Dir(shellPath)

	if err := installGlobalWrapper(piBinary, shellDir); err != nil {
		return shellPath, fmt.Errorf("writing global pi wrapper: %w", err)
	}

	if err := installCompletionScript(piBinary, shellDir); err != nil {
		return shellPath, fmt.Errorf("writing completion script: %w", err)
	}

	if err := ensureSourceLine(); err != nil {
		return shellPath, fmt.Errorf("updating shell config: %w", err)
	}

	if hasFishConfig() {
		if err := installFishFiles(cfg, piBinary, repoRoot, shellDir); err != nil {
			return shellPath, fmt.Errorf("writing fish shell files: %w", err)
		}
	}

	return shellPath, nil
}

// installGlobalWrapper writes the global pi() wrapper to ~/.pi/shell/_pi-wrapper.sh.
func installGlobalWrapper(piBinary, shellDir string) error {
	wrapperPath := filepath.Join(shellDir, piWrapperFile)
	content := GenerateGlobalWrapper(piBinary)
	return os.WriteFile(wrapperPath, []byte(content), 0o644)
}

// installFishFiles generates and writes fish-syntax shortcut, wrapper, and
// completion files, and ensures the fish source line is in config.fish.
func installFishFiles(cfg *config.ProjectConfig, piBinary, repoRoot, shellDir string) error {
	fishContent := GenerateShellFileWithDialect(cfg, piBinary, repoRoot, FishDialect{})
	fishPath, err := FishFilePath(cfg.Project)
	if err != nil {
		return err
	}
	if err := os.WriteFile(fishPath, []byte(fishContent), 0o644); err != nil {
		return fmt.Errorf("writing fish file: %w", err)
	}

	if err := installFishGlobalWrapper(piBinary, shellDir); err != nil {
		return err
	}

	if err := installFishCompletionScript(piBinary, shellDir); err != nil {
		return err
	}

	return ensureFishSourceLine()
}

// installFishGlobalWrapper writes the fish-syntax global pi wrapper.
func installFishGlobalWrapper(piBinary, shellDir string) error {
	wrapperPath := filepath.Join(shellDir, piFishWrapperFile)
	content := GenerateGlobalWrapperWithDialect(piBinary, FishDialect{})
	return os.WriteFile(wrapperPath, []byte(content), 0o644)
}

// GenerateCompletionScript builds a shell-agnostic completion setup script.
// It detects the current shell at source time and calls `pi completion <shell>`.
func GenerateCompletionScript(piBinary string) string {
	return fmt.Sprintf(`# PI shell completion — auto-generated by: pi shell — do not edit manually
if [ -n "$ZSH_VERSION" ]; then
  eval "$(%s completion zsh)"
elif [ -n "$BASH_VERSION" ]; then
  eval "$(%s completion bash)"
fi
`, piBinary, piBinary)
}

// installCompletionScript writes the completion setup to ~/.pi/shell/_pi-completion.sh.
func installCompletionScript(piBinary, shellDir string) error {
	completionPath := filepath.Join(shellDir, piCompletionFile)
	content := GenerateCompletionScript(piBinary)
	return os.WriteFile(completionPath, []byte(content), 0o644)
}

// GenerateFishCompletionScript builds a fish-syntax completion setup script.
func GenerateFishCompletionScript(piBinary string) string {
	return fmt.Sprintf("# PI fish completion — auto-generated by: pi shell — do not edit manually\n%s completion fish | source\n", piBinary)
}

// installFishCompletionScript writes the fish completion setup to ~/.pi/shell/_pi-completion.fish.
func installFishCompletionScript(piBinary, shellDir string) error {
	completionPath := filepath.Join(shellDir, piFishCompletionFile)
	content := GenerateFishCompletionScript(piBinary)
	return os.WriteFile(completionPath, []byte(content), 0o644)
}

// Uninstall removes the shortcuts file for the project and cleans up the source
// line and global wrapper if no other repos remain.
func Uninstall(project string) error {
	shellPath, err := ShellFilePath(project)
	if err != nil {
		return err
	}

	if err := os.Remove(shellPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("removing shell file: %w", err)
	}

	fishPath, err := FishFilePath(project)
	if err != nil {
		return err
	}
	if err := os.Remove(fishPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("removing fish file: %w", err)
	}

	dir, err := ShellFileDir()
	if err != nil {
		return err
	}
	entries, _ := os.ReadDir(dir)
	hasShFiles := false
	hasFishFiles := false
	for _, e := range entries {
		name := e.Name()
		if strings.HasSuffix(name, ".sh") && name != piWrapperFile && name != piCompletionFile {
			hasShFiles = true
		}
		if strings.HasSuffix(name, ".fish") && name != piFishWrapperFile && name != piFishCompletionFile {
			hasFishFiles = true
		}
	}

	if !hasShFiles {
		os.Remove(filepath.Join(dir, piWrapperFile))
		os.Remove(filepath.Join(dir, piCompletionFile))
		removeSourceLine()
	}

	if !hasFishFiles {
		os.Remove(filepath.Join(dir, piFishWrapperFile))
		os.Remove(filepath.Join(dir, piFishCompletionFile))
		removeFishSourceLine()
	}

	return nil
}

// ListInstalled returns all currently installed shortcut files (project names).
func ListInstalled() ([]string, error) {
	dir, err := ShellFileDir()
	if err != nil {
		return nil, err
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading shell directory: %w", err)
	}

	seen := make(map[string]bool)
	for _, e := range entries {
		name := e.Name()
		if isInfraFile(name) {
			continue
		}
		if strings.HasSuffix(name, ".sh") {
			seen[strings.TrimSuffix(name, ".sh")] = true
		} else if strings.HasSuffix(name, ".fish") {
			seen[strings.TrimSuffix(name, ".fish")] = true
		}
	}

	projects := make([]string, 0, len(seen))
	for p := range seen {
		projects = append(projects, p)
	}
	sort.Strings(projects)
	return projects, nil
}

// isInfraFile returns true for PI infrastructure files (wrappers, completions).
func isInfraFile(name string) bool {
	return name == piWrapperFile || name == piCompletionFile ||
		name == piFishWrapperFile || name == piFishCompletionFile
}

// shellConfigPaths returns the bash/zsh RC files to inject the source line into.
func shellConfigPaths() []string {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil
	}

	var paths []string
	zshrc := filepath.Join(home, ".zshrc")
	if _, err := os.Stat(zshrc); err == nil {
		paths = append(paths, zshrc)
	}
	bashrc := filepath.Join(home, ".bashrc")
	if _, err := os.Stat(bashrc); err == nil {
		paths = append(paths, bashrc)
	}

	// Always ensure at least .zshrc exists on macOS
	if len(paths) == 0 {
		paths = append(paths, zshrc)
	}
	return paths
}

// fishConfigPath returns the path to ~/.config/fish/config.fish, or "" if
// the home directory cannot be determined.
func fishConfigPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return filepath.Join(home, ".config", "fish", "config.fish")
}

// hasFishConfig returns true if ~/.config/fish/config.fish exists.
func hasFishConfig() bool {
	p := fishConfigPath()
	if p == "" {
		return false
	}
	_, err := os.Stat(p)
	return err == nil
}

// ensureFishSourceLine adds the PI source block to config.fish if not present.
func ensureFishSourceLine() error {
	cfgPath := fishConfigPath()
	if cfgPath == "" {
		return nil
	}

	data, err := os.ReadFile(cfgPath)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("reading %s: %w", cfgPath, err)
	}

	if strings.Contains(string(data), "# Added by PI") {
		return nil
	}

	f, err := os.OpenFile(cfgPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return fmt.Errorf("opening %s: %w", cfgPath, err)
	}
	if _, err := f.WriteString(fishSourceBlock); err != nil {
		f.Close()
		return fmt.Errorf("writing to %s: %w", cfgPath, err)
	}
	f.Close()
	return nil
}

// removeFishSourceLine removes the PI source block from config.fish.
func removeFishSourceLine() {
	cfgPath := fishConfigPath()
	if cfgPath == "" {
		return
	}
	data, err := os.ReadFile(cfgPath)
	if err != nil {
		return
	}
	content := string(data)
	if !strings.Contains(content, "# Added by PI") {
		return
	}
	cleaned := strings.Replace(content, fishSourceBlock, "", 1)
	os.WriteFile(cfgPath, []byte(cleaned), 0o644)
}

func ensureSourceLine() error {
	for _, rcPath := range shellConfigPaths() {
		data, err := os.ReadFile(rcPath)
		if err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("reading %s: %w", rcPath, err)
		}

		if strings.Contains(string(data), "# Added by PI") {
			continue
		}

		f, err := os.OpenFile(rcPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
		if err != nil {
			return fmt.Errorf("opening %s: %w", rcPath, err)
		}
		if _, err := f.WriteString(sourceBlock); err != nil {
			f.Close()
			return fmt.Errorf("writing to %s: %w", rcPath, err)
		}
		f.Close()
	}
	return nil
}

func removeSourceLine() {
	for _, rcPath := range shellConfigPaths() {
		data, err := os.ReadFile(rcPath)
		if err != nil {
			continue
		}
		content := string(data)
		if !strings.Contains(content, "# Added by PI") {
			continue
		}
		cleaned := strings.Replace(content, sourceBlock, "", 1)
		os.WriteFile(rcPath, []byte(cleaned), 0o644)
	}
}

// PrimaryRCFile returns the path to the user's primary shell RC file (.zshrc or .bashrc).
// Returns the first existing RC file, preferring .zshrc. Returns empty string if neither exists.
func PrimaryRCFile() string {
	paths := shellConfigPaths()
	if len(paths) > 0 {
		return paths[0]
	}
	return ""
}

func sortedShortcutNames(shortcuts map[string]config.Shortcut) []string {
	names := make([]string, 0, len(shortcuts))
	for name := range shortcuts {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
