package shell

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/vyper-tooling/pi/internal/config"
)

const (
	piShellDir  = ".pi/shell"
	sourceBlock = "\n# Added by PI — do not edit\nfor f in \"$HOME/.pi/shell/\"*.sh; do [ -f \"$f\" ] && source \"$f\"; done\n"
)

// ShellFileDir returns ~/.pi/shell/.
func ShellFileDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("getting home directory: %w", err)
	}
	return filepath.Join(home, piShellDir), nil
}

// ShellFilePath returns ~/.pi/shell/<project>.sh.
func ShellFilePath(project string) (string, error) {
	dir, err := ShellFileDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, project+".sh"), nil
}

// GenerateShellFile builds the content of the shortcuts shell file for a project.
// piBinary is the path to the pi binary (resolved by the caller).
// repoRoot is the absolute path to the project root.
func GenerateShellFile(cfg *config.ProjectConfig, piBinary, repoRoot string) string {
	if len(cfg.Shortcuts) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("# PI shortcuts for %s\n", cfg.Project))
	b.WriteString(fmt.Sprintf("# Repo: %s\n", repoRoot))
	b.WriteString("# Auto-generated by: pi shell — do not edit manually\n\n")

	names := sortedShortcutNames(cfg.Shortcuts)

	for _, name := range names {
		sc := cfg.Shortcuts[name]
		b.WriteString(generateFunction(name, sc, piBinary, repoRoot))
		b.WriteString("\n")
	}

	return b.String()
}

func generateFunction(name string, sc config.Shortcut, piBinary, repoRoot string) string {
	if sc.Anywhere {
		return fmt.Sprintf("function %s() {\n  %s run --repo %q %s \"$@\"\n}\n",
			name, piBinary, repoRoot, sc.Run)
	}
	return fmt.Sprintf("function %s() {\n  (cd %q && %s run %s \"$@\")\n}\n",
		name, repoRoot, piBinary, sc.Run)
}

// Install writes the shortcuts file and ensures the source line is in shell configs.
func Install(cfg *config.ProjectConfig, piBinary, repoRoot string) (string, error) {
	content := GenerateShellFile(cfg, piBinary, repoRoot)
	if content == "" {
		return "", fmt.Errorf("no shortcuts defined in pi.yaml")
	}

	shellPath, err := ShellFilePath(cfg.Project)
	if err != nil {
		return "", err
	}

	if err := os.MkdirAll(filepath.Dir(shellPath), 0o755); err != nil {
		return "", fmt.Errorf("creating shell directory: %w", err)
	}

	if err := os.WriteFile(shellPath, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("writing shell file: %w", err)
	}

	if err := ensureSourceLine(); err != nil {
		return shellPath, fmt.Errorf("updating shell config: %w", err)
	}

	return shellPath, nil
}

// Uninstall removes the shortcuts file for the project and cleans up the source
// line if no other repos remain.
func Uninstall(project string) error {
	shellPath, err := ShellFilePath(project)
	if err != nil {
		return err
	}

	if err := os.Remove(shellPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("removing shell file: %w", err)
	}

	dir, err := ShellFileDir()
	if err != nil {
		return err
	}
	entries, _ := os.ReadDir(dir)
	hasShFiles := false
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".sh") {
			hasShFiles = true
			break
		}
	}

	if !hasShFiles {
		removeSourceLine()
	}

	return nil
}

// ListInstalled returns all currently installed shortcut files (project names).
func ListInstalled() ([]string, error) {
	dir, err := ShellFileDir()
	if err != nil {
		return nil, err
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading shell directory: %w", err)
	}

	var projects []string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".sh") {
			projects = append(projects, strings.TrimSuffix(e.Name(), ".sh"))
		}
	}
	sort.Strings(projects)
	return projects, nil
}

// shellConfigPaths returns the RC files to inject the source line into.
func shellConfigPaths() []string {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil
	}

	var paths []string
	zshrc := filepath.Join(home, ".zshrc")
	if _, err := os.Stat(zshrc); err == nil {
		paths = append(paths, zshrc)
	}
	bashrc := filepath.Join(home, ".bashrc")
	if _, err := os.Stat(bashrc); err == nil {
		paths = append(paths, bashrc)
	}

	// Always ensure at least .zshrc exists on macOS
	if len(paths) == 0 {
		paths = append(paths, zshrc)
	}
	return paths
}

func ensureSourceLine() error {
	for _, rcPath := range shellConfigPaths() {
		data, err := os.ReadFile(rcPath)
		if err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("reading %s: %w", rcPath, err)
		}

		if strings.Contains(string(data), "# Added by PI") {
			continue
		}

		f, err := os.OpenFile(rcPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
		if err != nil {
			return fmt.Errorf("opening %s: %w", rcPath, err)
		}
		if _, err := f.WriteString(sourceBlock); err != nil {
			f.Close()
			return fmt.Errorf("writing to %s: %w", rcPath, err)
		}
		f.Close()
	}
	return nil
}

func removeSourceLine() {
	for _, rcPath := range shellConfigPaths() {
		data, err := os.ReadFile(rcPath)
		if err != nil {
			continue
		}
		content := string(data)
		if !strings.Contains(content, "# Added by PI") {
			continue
		}
		cleaned := strings.Replace(content, sourceBlock, "", 1)
		os.WriteFile(rcPath, []byte(cleaned), 0o644)
	}
}

func sortedShortcutNames(shortcuts map[string]config.Shortcut) []string {
	names := make([]string, 0, len(shortcuts))
	for name := range shortcuts {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
