package shell

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/vyper-tooling/pi/internal/config"
)

const (
	piShellDir      = ".pi/shell"
	piWrapperFile   = "_pi-wrapper.sh"
	piCompletionFile = "_pi-completion.sh"
	sourceBlock     = "\n# Added by PI — do not edit\nfor f in \"$HOME/.pi/shell/\"*.sh; do [ -f \"$f\" ] && source \"$f\"; done\n"
)

// ShellFileDir returns ~/.pi/shell/.
func ShellFileDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("getting home directory: %w", err)
	}
	return filepath.Join(home, piShellDir), nil
}

// ShellFilePath returns ~/.pi/shell/<project>.sh.
func ShellFilePath(project string) (string, error) {
	dir, err := ShellFileDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, project+".sh"), nil
}

// GenerateShellFile builds the content of the shortcuts shell file for a project.
// piBinary is the path to the pi binary (resolved by the caller).
// repoRoot is the absolute path to the project root.
func GenerateShellFile(cfg *config.ProjectConfig, piBinary, repoRoot string) string {
	if len(cfg.Shortcuts) == 0 {
		return ""
	}

	var b strings.Builder
	b.WriteString(fmt.Sprintf("# PI shortcuts for %s\n", cfg.Project))
	b.WriteString(fmt.Sprintf("# Repo: %s\n", repoRoot))
	b.WriteString("# Auto-generated by: pi shell — do not edit manually\n\n")

	b.WriteString(generateSetupHelper(piBinary, repoRoot))
	b.WriteString("\n")

	names := sortedShortcutNames(cfg.Shortcuts)

	for _, name := range names {
		sc := cfg.Shortcuts[name]
		b.WriteString(generateFunction(name, sc, piBinary, repoRoot))
		b.WriteString("\n")
	}

	return b.String()
}

// generateSetupHelper emits a pi-setup-<project> function that wraps `pi setup`
// with the eval pattern so that post-setup shell sourcing works automatically.
func generateSetupHelper(piBinary, repoRoot string) string {
	safeProject := strings.ReplaceAll(filepath.Base(repoRoot), " ", "-")
	return fmt.Sprintf(`function pi-setup-%s() {
  local _pi_eval_file
  _pi_eval_file="$(mktemp)"
  (cd %q && PI_PARENT_EVAL_FILE="$_pi_eval_file" %s setup "$@")
  local _pi_exit=$?
  if [ -s "$_pi_eval_file" ]; then
    source "$_pi_eval_file"
  fi
  rm -f "$_pi_eval_file"
  return $_pi_exit
}
`, safeProject, repoRoot, piBinary)
}

func generateFunction(name string, sc config.Shortcut, piBinary, repoRoot string) string {
	if len(sc.With) > 0 {
		return generateFunctionWithInputs(name, sc, piBinary, repoRoot)
	}

	var piCmd string
	if sc.Anywhere {
		piCmd = fmt.Sprintf("PI_PARENT_EVAL_FILE=\"$_pi_eval_file\" %s run --repo %q %s \"$@\"", piBinary, repoRoot, sc.Run)
	} else {
		piCmd = fmt.Sprintf("(cd %q && PI_PARENT_EVAL_FILE=\"$_pi_eval_file\" %s run %s \"$@\")", repoRoot, piBinary, sc.Run)
	}

	return fmt.Sprintf(`function %s() {
  local _pi_eval_file
  _pi_eval_file="$(mktemp)"
  %s
  local _pi_exit=$?
  if [ -s "$_pi_eval_file" ]; then
    source "$_pi_eval_file"
  fi
  rm -f "$_pi_eval_file"
  return $_pi_exit
}
`, name, piCmd)
}

func generateFunctionWithInputs(name string, sc config.Shortcut, piBinary, repoRoot string) string {
	withNames := sortedKeys(sc.With)

	var withParts []string
	for _, k := range withNames {
		v := sc.With[k]
		if isPositionalRef(v) {
			argNum := v[1:]
			withParts = append(withParts, fmt.Sprintf("--with %s=\"$%s\"", k, argNum))
		} else {
			withParts = append(withParts, fmt.Sprintf("--with %s=%q", k, v))
		}
	}
	withStr := strings.Join(withParts, " ")

	var piCmd string
	if sc.Anywhere {
		piCmd = fmt.Sprintf("PI_PARENT_EVAL_FILE=\"$_pi_eval_file\" %s run --repo %q %s %s", piBinary, repoRoot, sc.Run, withStr)
	} else {
		piCmd = fmt.Sprintf("(cd %q && PI_PARENT_EVAL_FILE=\"$_pi_eval_file\" %s run %s %s)", repoRoot, piBinary, sc.Run, withStr)
	}

	return fmt.Sprintf(`function %s() {
  local _pi_eval_file
  _pi_eval_file="$(mktemp)"
  %s
  local _pi_exit=$?
  if [ -s "$_pi_eval_file" ]; then
    source "$_pi_eval_file"
  fi
  rm -f "$_pi_eval_file"
  return $_pi_exit
}
`, name, piCmd)
}

func isPositionalRef(v string) bool {
	if len(v) < 2 || v[0] != '$' {
		return false
	}
	for _, c := range v[1:] {
		if c < '0' || c > '9' {
			return false
		}
	}
	return true
}

func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// GenerateGlobalWrapper builds the content of the global pi() shell function.
// This wraps every `pi` invocation with the eval pattern so parent_shell steps
// work for all `pi run` calls, not just shortcuts.
func GenerateGlobalWrapper(piBinary string) string {
	return fmt.Sprintf(`# PI global wrapper — enables parent_shell steps for all pi invocations
# Auto-generated by: pi shell — do not edit manually
function pi() {
  local _pi_eval_file
  _pi_eval_file="$(mktemp)"
  PI_PARENT_EVAL_FILE="$_pi_eval_file" command %s "$@"
  local _pi_exit=$?
  if [ -s "$_pi_eval_file" ]; then
    source "$_pi_eval_file"
  fi
  rm -f "$_pi_eval_file"
  return $_pi_exit
}
`, piBinary)
}

// Install writes the shortcuts file, the global pi() wrapper,
// and ensures the source line is in shell configs.
func Install(cfg *config.ProjectConfig, piBinary, repoRoot string) (string, error) {
	content := GenerateShellFile(cfg, piBinary, repoRoot)
	if content == "" {
		return "", fmt.Errorf("no shortcuts defined in pi.yaml")
	}

	shellPath, err := ShellFilePath(cfg.Project)
	if err != nil {
		return "", err
	}

	if err := os.MkdirAll(filepath.Dir(shellPath), 0o755); err != nil {
		return "", fmt.Errorf("creating shell directory: %w", err)
	}

	if err := os.WriteFile(shellPath, []byte(content), 0o644); err != nil {
		return "", fmt.Errorf("writing shell file: %w", err)
	}

	shellDir := filepath.Dir(shellPath)

	if err := installGlobalWrapper(piBinary, shellDir); err != nil {
		return shellPath, fmt.Errorf("writing global pi wrapper: %w", err)
	}

	if err := installCompletionScript(piBinary, shellDir); err != nil {
		return shellPath, fmt.Errorf("writing completion script: %w", err)
	}

	if err := ensureSourceLine(); err != nil {
		return shellPath, fmt.Errorf("updating shell config: %w", err)
	}

	return shellPath, nil
}

// installGlobalWrapper writes the global pi() wrapper to ~/.pi/shell/_pi-wrapper.sh.
func installGlobalWrapper(piBinary, shellDir string) error {
	wrapperPath := filepath.Join(shellDir, piWrapperFile)
	content := GenerateGlobalWrapper(piBinary)
	return os.WriteFile(wrapperPath, []byte(content), 0o644)
}

// GenerateCompletionScript builds a shell-agnostic completion setup script.
// It detects the current shell at source time and calls `pi completion <shell>`.
func GenerateCompletionScript(piBinary string) string {
	return fmt.Sprintf(`# PI shell completion — auto-generated by: pi shell — do not edit manually
if [ -n "$ZSH_VERSION" ]; then
  eval "$(%s completion zsh)"
elif [ -n "$BASH_VERSION" ]; then
  eval "$(%s completion bash)"
fi
`, piBinary, piBinary)
}

// installCompletionScript writes the completion setup to ~/.pi/shell/_pi-completion.sh.
func installCompletionScript(piBinary, shellDir string) error {
	completionPath := filepath.Join(shellDir, piCompletionFile)
	content := GenerateCompletionScript(piBinary)
	return os.WriteFile(completionPath, []byte(content), 0o644)
}

// Uninstall removes the shortcuts file for the project and cleans up the source
// line and global wrapper if no other repos remain.
func Uninstall(project string) error {
	shellPath, err := ShellFilePath(project)
	if err != nil {
		return err
	}

	if err := os.Remove(shellPath); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("removing shell file: %w", err)
	}

	dir, err := ShellFileDir()
	if err != nil {
		return err
	}
	entries, _ := os.ReadDir(dir)
	hasProjectFiles := false
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".sh") && e.Name() != piWrapperFile && e.Name() != piCompletionFile {
			hasProjectFiles = true
			break
		}
	}

	if !hasProjectFiles {
		os.Remove(filepath.Join(dir, piWrapperFile))
		os.Remove(filepath.Join(dir, piCompletionFile))
		removeSourceLine()
	}

	return nil
}

// ListInstalled returns all currently installed shortcut files (project names).
func ListInstalled() ([]string, error) {
	dir, err := ShellFileDir()
	if err != nil {
		return nil, err
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("reading shell directory: %w", err)
	}

	var projects []string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".sh") && e.Name() != piWrapperFile && e.Name() != piCompletionFile {
			projects = append(projects, strings.TrimSuffix(e.Name(), ".sh"))
		}
	}
	sort.Strings(projects)
	return projects, nil
}

// shellConfigPaths returns the RC files to inject the source line into.
func shellConfigPaths() []string {
	home, err := os.UserHomeDir()
	if err != nil {
		return nil
	}

	var paths []string
	zshrc := filepath.Join(home, ".zshrc")
	if _, err := os.Stat(zshrc); err == nil {
		paths = append(paths, zshrc)
	}
	bashrc := filepath.Join(home, ".bashrc")
	if _, err := os.Stat(bashrc); err == nil {
		paths = append(paths, bashrc)
	}

	// Always ensure at least .zshrc exists on macOS
	if len(paths) == 0 {
		paths = append(paths, zshrc)
	}
	return paths
}

func ensureSourceLine() error {
	for _, rcPath := range shellConfigPaths() {
		data, err := os.ReadFile(rcPath)
		if err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("reading %s: %w", rcPath, err)
		}

		if strings.Contains(string(data), "# Added by PI") {
			continue
		}

		f, err := os.OpenFile(rcPath, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
		if err != nil {
			return fmt.Errorf("opening %s: %w", rcPath, err)
		}
		if _, err := f.WriteString(sourceBlock); err != nil {
			f.Close()
			return fmt.Errorf("writing to %s: %w", rcPath, err)
		}
		f.Close()
	}
	return nil
}

func removeSourceLine() {
	for _, rcPath := range shellConfigPaths() {
		data, err := os.ReadFile(rcPath)
		if err != nil {
			continue
		}
		content := string(data)
		if !strings.Contains(content, "# Added by PI") {
			continue
		}
		cleaned := strings.Replace(content, sourceBlock, "", 1)
		os.WriteFile(rcPath, []byte(cleaned), 0o644)
	}
}

// PrimaryRCFile returns the path to the user's primary shell RC file (.zshrc or .bashrc).
// Returns the first existing RC file, preferring .zshrc. Returns empty string if neither exists.
func PrimaryRCFile() string {
	paths := shellConfigPaths()
	if len(paths) > 0 {
		return paths[0]
	}
	return ""
}

func sortedShortcutNames(shortcuts map[string]config.Shortcut) []string {
	names := make([]string, 0, len(shortcuts))
	for name := range shortcuts {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
